version: '3.0'

services: 

  main:
    container_name: main
    build:
      context: .
    env_file:
      - ./config/.development.env
    volumes:
      -.:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: yarn start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./config/.development.env
    environment:
      PG_DATA: /var/lib/postresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata: /var/lib/postresql/data
    restart: always

  volumes:
    pgdata: